// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...



class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVloabPfNk5zX20GFTXMyi8bfXQy7eekM',
    appId: '1:916349786247:web:104fb06c96c4c56ea60022',
    messagingSenderId: '916349786247',
    projectId: 'stayfit-a5728',
    authDomain: 'stayfit-a5728.firebaseapp.com',
    storageBucket: 'stayfit-a5728.appspot.com',
  );

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ5YmdxCLBa5QYgWC4bOroPl_ZR1iA9ws',
    appId: '1:916349786247:android:2f1c00428f23343ca60022',
    messagingSenderId: '916349786247',
    projectId: 'stayfit-a5728',
    storageBucket: 'stayfit-a5728.appspot.com',
  );

  static  FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQg-WsuT7IPef5B_2MI5gWS8_IfFlOiN4',
    appId: '1:916349786247:ios:4290249c46896d21a60022',
    messagingSenderId: '916349786247',
    projectId: 'stayfit-a5728',
    storageBucket: 'stayfit-a5728.appspot.com',
    iosBundleId: 'com.example.stayfit',
  );

  static  FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQg-WsuT7IPef5B_2MI5gWS8_IfFlOiN4',
    appId: '1:916349786247:ios:c810ea275e089819a60022',
    messagingSenderId: '916349786247',
    projectId: 'stayfit-a5728',
    storageBucket: 'stayfit-a5728.appspot.com',
    iosBundleId: 'com.example.stayfit.RunnerTests',
  );
}
